style_edition = "2024"
newline_style = "Unix"

merge_derives = false
use_field_init_shorthand = true
match_block_trailing_comma = true
overflow_delimited_expr = true
where_single_line = true
single_line_if_else_max_width = 80
chain_width = 80
